version: "3.9"

services:
  eureka-server:
    image: ghcr.io/athenhub/eureka-server:latest
    container_name: eureka-server
    ports:
      - "9150:9150"
    environment:
      - HOSTNAME=eureka-server
      - EUREKA_URL=http://eureka-server:9150/eureka
    networks:
      - msa-network

  config-server:
    image: ghcr.io/athenhub/config-server:latest
    container_name: config-server
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_URL=http://eureka-server:9150/eureka
    networks:
      - msa-network

  gateway-server:
    image: ghcr.io/athenhub/gateway-server:latest
    container_name: gateway-server
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka-server:9150/eureka
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
