version: "3.9"

services:
  eureka-server:
    image: ghcr.io/athenhub/eureka-server:latest
    container_name: eureka-server
    ports:
      - "9150:9150"
    environment:
      EUREKA_INSTANCE_HOSTNAME: '3.38.80.105'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka-server:9150/eureka'
    networks:
      - msa-network

  config-server:
    image: ghcr.io/athenhub/config-server:latest
    container_name: config-server
    depends_on:
      - eureka-server
    ports:
      - "8888:9100"
    environment:
      EUREKA_INSTANCE_HOSTNAME: '3.38.80.105'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka-server:9150/eureka'
    networks:
      - msa-network

  gateway-server:
    image: ghcr.io/athenhub/gateway-server:latest
    container_name: gateway-server
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8080:9000"
    environment:
      EUREKA_INSTANCE_HOSTNAME: '3.38.80.105'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka-server:9150/eureka'
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
